name: Python package

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        pipx ensurepath && pipx install poetry==1.7.1
        poetry install && poetry build
    - name: Lint with mypy
      run: |
        poetry run mypy .
    - name: Test with pytest
      run: |
        poetry run pytest
